obj-$(CONFIG_MBX) += mbxaccess.o iphonelcd.o 

mbxaccess-objs	:= mbxaccess_main.o malloc_debug.o mbxaccess_iowrapper.o mbxaccess_mbxmem.o mbxaccess_memwrapper.o \
	mbxaccess_mmapwrapper.o mbxaccess_procwrapper.o mbxaccess_pvrclassjtable.o mbxaccess_timerwrapper.o \
	mbxaccess_virtmemwrapper.o mmap.o mm.o mutex.o pvr_debug.o

iphonelcd-objs := iphonelcd_displayclass.o iphonelcd_linux.o

