#
# Makefile for the linux kernel.
#

obj-y					+= iphone.o irq.o timer.o \
							power.o clock.o dma.o \
							gpio.o i2c.o spi.o \
							usb.o vfl.o ftl.o nand.o \
							pcf50633.o pcf50635.o suspend.o

